### PR TITLE
Don't add './' if the path already starts with '../'

### PR DESCRIPTION
**Pull request by robindijkhof**
'./../something' is the same as '../something'

### CODE REVIEW

**Comment by SamVerschueren** [comment]
This PR fixes #37. Any chance of adding or reviewing this change?

@soates I totally understand if you have a busy life and don't have time looking into maintaining this (right now). Think about adding someone as a co-maintainer of the repository to share ownership so that the extensions benefits from it with new improvements and fixes (like this one).

**Comment by Lindsor** [comment]
Any update on this? Id like this in as well

**Comment by thomaswmanion** [comment]
Think the dude raged quit GitHub. Might need a new owner of this.

**Comment by soates** [comment]
Will merge this in today.

**Comment by thorn0** [comment]
Has it really been fixed? I still see the old behavior:
image

**Comment by Lindsor** [comment]
Nope still seeing it as well

**Pull request merged**
